config/routes.rb
DemoApp::Application.routes.draw do
  resources :subjects

  root :to => 'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'

  match '/help',    :to => 'static_pages#help',    :via => 'get'
  match '/about',    :to => 'static_pages#about',    :via => 'get'
  match '/contact',    :to => 'static_pages#contact',    :via => 'get'
  match '/signup',  :to => 'users#new', :via => 'get'
    match '/signin',  :to => 'sessions#new',  :via => 'get'
  match '/signout', :to => 'sessions#destroy',  :via => 'delete'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy,
                                :index, :update, :edit, :new, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :birth_day, :birth_month, :birth_year, :name, :user_id, :birth_time
  validates :user_id, presence: true
  validates :birth_year, presence: true
  validates :birth_month, presence: true
  validates :birth_day, presence: true
  validates :birth_time, presence: true

  has_many :micropost_subjects, :foreign_key => "subject_id", :dependent => :destroy
  has_many :microposts, :through => :micropost_subjects

  belongs_to :user

  def has_birth_date?
    birth_month && birth_day && birth_year
  end

end

app/controllers/subjects_controller.rb
require 'will_paginate/array'

class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])
    # TODO optimize
    @microposts = @subject.microposts.sort{|a,b|
              a_write_time = a.write_time.blank? ? a.created_at : a.write_time
              b_write_time = b.write_time.blank? ? b.created_at : b.write_time
              b_write_time <=> a_write_time
            }.paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    #@subject = Subject.find(params[:id])
    @subject = current_user.subjects.find(params[:id])
  end

  def create
    params[:subject][:birth_time] = DateTime.new(params[:subject][:birth_year].to_i,params[:subject][:birth_month].to_i,params[:subject][:birth_day].to_i)
    @subject = current_user.subjects.build(params[:subject])
    if @subject.save
      flash[:success] = "Subject created!"
    else
      flash[:error] = "Sorry, failed to save subject"
    end
    redirect_to "/users/#{current_user.id}"
  end

  # PUT /subjects/1
  def update
    @subject = Subject.find(params[:id])
    user = @subject.user

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to user_path(user), notice: 'Subject was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /subjects/1
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    redirect_to "/users/#{current_user.id}"
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def friendly_subject_age(subject, tz_offset = nil)
    begin
      subject_birth_date = Time.zone.local(subject.birth_year.to_i, subject.birth_month.to_i, subject.birth_day.to_i)

      if tz_offset
        zone = ActiveSupport::TimeZone[tz_offset.to_i]
      else
        zone = ActiveSupport::TimeZone.new('Pacific Time (US & Canada)')
      end
      today = zone.today

      if subject_birth_date < today
        return DOTIW::DOTIW.new.distance_of_time_in_words(subject_birth_date, today, true, {:only => ["years", "months", "days"]}) + " old"
      else
        return "Not yet born"
      end
    rescue
      return nil
    end
  end

  def written_at_age(micropost, subject, tz_offset =nil)
    begin
      subject_birth_date = subject.birth_time
      if tz_offset
        zone = ActiveSupport::TimeZone[tz_offset.to_i]
      else
        zone = ActiveSupport::TimeZone.new('Pacific Time (US & Canada)')
      end

      if micropost.write_time.present?
        written_date = micropost.write_time
      else
        written_date = micropost.created_at.in_time_zone(zone)
      end
      if subject_birth_date < written_date
        return DOTIW::DOTIW.new.distance_of_time_in_words(subject_birth_date, written_date, true, {:only => ["years", "months", "days"]}) + " old"
      else
        return "Not yet born"
      end
    rescue
      return nil
    end
  end

end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_month %><br />
    <%= f.text_field :birth_month %>
  </div>
  <div class="field">
    <%= f.label :birth_day %><br />
    <%= f.text_field :birth_day %>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br />
    <%= f.text_field :birth_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div class="clearfix;" style="border-bottom: 1px solid #e8e8e8; ">
  <!--
      https://github.com/radar/dotiw
      DOTIW::DOTIW.new.distance_of_time_in_words(child_birth_date, today, true, {:only => ["years", "months", "days"]}) + " old"
       -->
      <span style="margin: 5px 0 5px 0; ">
        <%= link_to subject.name, subject_path(subject.id), {title: subject.name, class: "bluelink"} %>
        <% if current_user?(subject.user) %>
         (<%= link_to "Edit", edit_subject_path(subject), {title: subject.name, class: "bluelink"}%>,
          <%= link_to "Delete", subject, method: :delete,
                                            data: { confirm: "You sure?" },
                                            title: subject.name, class: "bluelink" %>)
        <% end %>
      </span>
      <span style="margin: 5px 0 5px 0">
        <% if subject.has_birth_date? %>
          <%= friendly_subject_age(subject) %>
        <% end %>
      </span>

</div>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birth month</th>
    <th>Birth day</th>
    <th>Birth year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.name %></td>
    <td><%= subject.birth_month %></td>
    <td><%= subject.birth_day %></td>
    <td><%= subject.birth_year %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<div class="row">
  <aside class="span5">
    <p id="notice"><%= notice %></p>

    <p>
      <b>Name:</b>
      <%= @subject.name %>
    </p>

    <p>
      <b>Birth month:</b>
      <%= @subject.birth_month %>
    </p>

    <p>
      <b>Birth day:</b>
      <%= @subject.birth_day %>
    </p>

    <p>
      <b>Birth year:</b>
      <%= @subject.birth_year %>
    </p>

    <%= link_to 'Edit', edit_subject_path(@subject) %> |
    <%= link_to 'Back', (link_back_or @subject rescue nil)  %>
  </aside>

  <div class="span7">
    <% if @subject.microposts.any? %>
      <h3>Microposts (<%= @subject.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>

  </div>
</div>