config/routes.rb
DemoApp::Application.routes.draw do
  resources :subjects

  root :to => 'static_pages#home'
  match '/', to: 'static_pages#home', via: 'get'

  match '/help',    :to => 'static_pages#help',    :via => 'get'
  match '/about',    :to => 'static_pages#about',    :via => 'get'
  match '/contact',    :to => 'static_pages#contact',    :via => 'get'
  match '/signup',  :to => 'users#new', :via => 'get'
    match '/signin',  :to => 'sessions#new',  :via => 'get'
  match '/signout', :to => 'sessions#destroy',  :via => 'delete'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy,
                                :index, :update, :edit, :new, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  attr_accessible :content, :user_id, :subject_id, :write_month, :write_day, :write_year, :write_time
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  validates :write_month, numericality: true, if: :write_month? # TODO: should be integer string
  validates :write_day, numericality: true, if: :write_day?
  validates :write_year, numericality: true, if: :write_year?
  validates :write_time, presence: true

  has_many :micropost_subjects, :foreign_key => "micropost_id", :dependent => :destroy
  has_many :subjects, :through => :micropost_subjects

  belongs_to :user
  belongs_to :subject

  # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                             WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user,   only: :destroy

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end
=begin


  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end
=end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    params[:micropost][:write_time] = DateTime.new(params[:micropost][:write_year].to_i,params[:micropost][:write_month].to_i,params[:micropost][:write_day].to_i)

    @micropost = current_user.microposts.build(params[:micropost])
    success = @micropost.save
    # Due to @micropost.micropost_subjects micropost_id is nil, move @micropost.save
    # after subject_ids assignment will cause @micropost.save fail
    @micropost.subject_ids = params[:selected_subject_ids]
    success = @micropost.save if success
    if success
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
=begin
  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end
=end
=begin
{"utf8"=>"✓", "_method"=>"put", "authenticity_token"=>"2oJ7TdPVzqVgUeNwq9QEehiK2t5bZYIy0peyruxvgH4=",
"micropost"=>{"content"=>"xlu post 1", "user_id"=>"101", "subject_id"=>""},
"selected_subject_ids"=>["11"],
"commit"=>"Update Micropost", "action"=>"update", "controller"=>"microposts", "id"=>"301"}
=end
  def update
    @micropost = current_user.microposts.find(params[:id])
    @micropost.subject_ids = params[:selected_subject_ids]
    params[:micropost][:write_time] = DateTime.new(params[:micropost][:write_year].to_i,params[:micropost][:write_month].to_i,params[:micropost][:write_day].to_i)

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        flash[:notice] = 'Micropost was successfully updated.'
        format.html { redirect_back_or @micropost }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

  def correct_user
    @micropost = current_user.microposts.where(id: params[:id]).first
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>

  <%= render :partial => "/shared/set_post_write_time", :locals => {:f => f} %>
  <%= render :partial => "/shared/select_subject_for_post", :locals => {:micropost => @micropost }%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <%= render :partial => "/microposts/micropost_subjects", :locals => {:micropost => micropost, :written_for => "Written for"} %>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>

  <% if current_user?(micropost.user) %>
    <%= link_to 'Edit', edit_micropost_path(micropost) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/microposts/_micropost_subjects.html.erb
<% if micropost.subjects.count > 0 %>
  <%= written_for %>
<% end %>

<% micropost.subjects.each do |subject| %>
  <%= subject.name %>
  (<%= written_at_age(micropost, subject) %>)
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', (link_back_or @micropost rescue nil) %>